"""Declared substitute codes — the one place a "hidden missing value" is named.

Rahm & Do's **missing values** class (Table 2, attribute scope, instance
level) has as its canonical example not a null but a dummy value,
``phone=9999-999999``, with the reason "unavailable values during data entry
(dummy values or null)". Table 3 gives the detection rule in one line:
"presence of default value may indicate real value is missing".

Van den Broeck names why these are the hardest thing in the dataset to see.
They are **erroneous inliers** — "data points generated by error but falling
within the expected range" — and he predicts the outcome: "Erroneous inliers
will often escape detection." No range check finds them, because there is
nothing out of range. $250,001 is a perfectly plausible household income. Q1
is a perfectly plausible quarter.

Two of this project's defects were filed as unrelated findings and are the
same one:

    median_household_income = 250_001   the Census substituted a top code
    open_quarter = Q1                   we substituted a default

They differ only in who did the substituting. So they are declared together,
in one registry, detected by one function and guarded by one build gate
(``warehouse/flag_gate.py``). Adding a third source is adding a row here.

What this module does NOT do
----------------------------
**It never changes a value.** Screening and editing are separate acts in Van
den Broeck's loop, and conflating them is how good data gets deleted. Every
entry here emits a boolean beside the value and leaves the value alone, so
the treatment is reversible by dropping a column and the consumer decides.

It is also not the place for *impossible* values. The six large negative ACS
sentinels (``ingest/census_api.SENTINELS``) are out of range by construction,
are already mapped to NULL at read, and are Van den Broeck's "impossible"
band rather than his inlier band — different diagnosis, different treatment,
and that one is correct as it stands.

The invalid-code convention
---------------------------
Fellegi & Holt §2 note 3(a) and note 6 ask for a *declared representation* for
"not a value": "reserve one extra code per field for all the invalid codes of
Field i", so that a record with one becomes a countable, named state rather
than an arithmetic accident. ``ABSENT`` is that code here. It is what makes
"this quarter is a convention" a fact in the data instead of an inference
nobody can make.

One place this convention is still owed and not paid:
``warehouse/facilities.py`` ends with ``enabled.fillna(False)``, which
collapses "not covered by any known catchment" and "known not to be served"
into the same FALSE. Fellegi & Holt note 6 draws exactly that line — "the code
value 'blank' may or may not be among the set of possible values of a field".
Separating them changes the dtype and the meaning of the fitted target, so it
is a modelling decision and is deliberately not made here. See
``docs/data/CLEANING_CHANGELOG.md``.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

#: A value the publisher substitutes for one it will not report, at the top
#: of the range.
TOP = "top"
#: The same at the bottom of the range.
BOTTOM = "bottom"
#: No value was reported at all, and the pipeline substitutes a default
#: downstream. The flag records that the default is a convention.
ABSENT = "absent"


@dataclass(frozen=True)
class Sentinel:
    """One declared substitute code on one field of one source.

    ``code`` is the literal value for :data:`TOP` / :data:`BOTTOM` and is
    ``None`` for :data:`ABSENT`, where the substitution happens downstream of
    the source rather than inside it.
    """

    field: str
    kind: str
    code: float | None
    flag: str
    why: str

    def detect(self, series: pd.Series) -> pd.Series:
        """Which rows carry the substitute code. Never edits the series."""
        if self.kind == TOP:
            return series.ge(self.code).fillna(False)
        if self.kind == BOTTOM:
            return series.le(self.code).fillna(False)
        if self.kind == ABSENT:
            return series.isna()
        raise ValueError(f"unknown sentinel kind {self.kind!r}")


#: Every substitute code this pipeline knows about, by source.
#:
#: ACS counts measured on the 2023 release (33,772 ZCTAs): 83 / 20 / 86 / 23.
#: The bottom codes had never been looked for before 2026-09-13; the audit
#: found them, not the code.
#:
#: The facility entry is the same class arriving from the other direction —
#: the source reports nothing and `warehouse/facility_load.py` substitutes Q1,
#: on 19 of 43 rows (44.2%), which is what puts 35.47% of fitted events in Q1
#: against 25% expected under uniformity.
REGISTRY: dict[str, tuple[Sentinel, ...]] = {
    "acs5_zcta": (
        Sentinel("median_home_value", TOP, 2_000_001,
                 "median_home_value_topcoded",
                 "ACS publishes its highest tabulation code when the true "
                 "median is above it; Palo Alto and Atherton both report "
                 "$2,000,001. A lower bound, not a measurement."),
        Sentinel("median_home_value", BOTTOM, 9_999,
                 "median_home_value_bottomcoded",
                 "The matching bottom code. An upper bound."),
        Sentinel("median_household_income", TOP, 250_001,
                 "median_household_income_topcoded",
                 "As above at $250,001. cost/daganzo.py drives daily_parcels "
                 "through an income elasticity, so reading the code as a "
                 "point estimate understates parcel demand and therefore "
                 "understates cost advantage, one-directionally."),
        Sentinel("median_household_income", BOTTOM, 2_499,
                 "median_household_income_bottomcoded",
                 "The matching bottom code at $2,499."),
    ),
    "facility_panel": (
        Sentinel("open_quarter", ABSENT, None, "open_quarter_imputed",
                 "No quarter was collected. warehouse/facility_load.py dates "
                 "the event to Q1 by convention rather than dropping the row; "
                 "the flag is what lets a model tell the convention from a "
                 "reported date."),
    ),
}


def flags_for(source: str) -> tuple[str, ...]:
    """The flag column names one source contributes."""
    return tuple(s.flag for s in REGISTRY.get(source, ()))


def all_flags() -> dict[str, str]:
    """Every declared flag, mapped to the source that declares it."""
    return {s.flag: source for source, entries in REGISTRY.items()
            for s in entries}


def flag_sentinels(frame: pd.DataFrame, source: str) -> pd.DataFrame:
    """Add the declared flags for ``source``, changing no value.

    A field the frame does not carry is skipped rather than fabricated —
    ``acs1_metro`` has no ``median_home_value`` and must not gain a flag for
    one. Mutates and returns ``frame``, matching the surrounding ingest style.
    """
    for sentinel in REGISTRY.get(source, ()):
        if sentinel.field in frame.columns:
            frame[sentinel.flag] = sentinel.detect(frame[sentinel.field])
    return frame
